adobe/svg-native-viewer

svgnative/include/SVGRenderer.h, svgnative/ports/cg/CGSVGRenderer.cpp, svgnative/ports/cg/CGSVGRenderer.h, svgnative/ports/skia/SkiaSVGRenderer.cpp, svgnative/ports/skia/SkiaSVGRenderer.h, svgnative/ports/string/StringSVGRenderer.cpp, svgnative/ports/string/StringSVGRenderer.h, svgnative/src/SVGDocumentImpl.cpp, svgnative/src/SVGDocumentImpl.h, svgnative/test/clipping.svg, svgnative/test/clipping.txt
The implementation is based on the latest specification draft of SVG Native. Only one clipping shape is supported. Therefore, we don't need to create the union of paths.
=> Better clipping support

svgnative/src/SVGDocumentImpl.cpp
Maybe mistakenly it has been set to ImageEncoding::kPNG.
=> bugfix: encoding = ImageEncoding::kJPEG, if dataURL declares its content as jpg or jpeg.

.gitmodules
currently, .gitmodule sets the protocol for 3rd party repos to ssh, like, "url = git@github.com:adobe/stylesheet.git". I suggest to change it to https, like, "url = https://github.com/adobe/stylesheet.git". It could be slightly more convenient to download & compile on the systems without registered ssh keys.
=> change protocol to access 3rd party repos, from ssh to https.

svgnative/src/DeprecatedSVGDocumentImpl.cpp, svgnative/src/SVGDocumentImpl.cpp
Giving this file https://www.w3.org/TR/SVG11/images/paths/cubic01.svg to the example "testSVGNative" for the text backend, I got a crash like this.
(gdb) run moretest/cubic01.svg cubic01.txt
Starting program: /home/sssa/redhat/BUILD/svg-native-viewer/svgnative/Build/linux-20190516/example/testText/testSVGNative moretest/cubic01.svg cubic01.txt
Program received signal SIGSEGV, Segmentation fault.
0x00005555555605cc in std::__uniq_ptr_impl<SVGNative::SVGDocumentImpl, std::default_delete<SVGNative::SVGDocumentImpl> >::_M_ptr (this=0x0) at /usr/include/c++/7/bits/unique_ptr.h:147
147           pointer    _M_ptr() const { return std::get<0>(_M_t); }
(gdb) where
#0  0x00005555555605cc in std::__uniq_ptr_impl<SVGNative::SVGDocumentImpl, std::default_delete<SVGNative::SVGDocumentImpl> >::_M_ptr …
=> Prevent a crash caused by empty css element list.

svgnative/ports/skia/SkiaSVGRenderer.cpp
The addition of stroke-width feature might be far simpler than that of dashed-array, I apologize that I have not requested this before. It's just because of my laziness to read the API reference of Skia.
=> add stroke-width feature to Skia backend

svgnative/src/SVGDocumentImpl.cpp
At the moment, the library doesn't take care of any viewbox shifting as @mpsuzuki illustrates in #33. This is one way to fix that which works for me, though I am not sure whether it's the right way.
=> Take into account viewbox translations too.

svgnative/src/SVGDocumentImpl.cpp
This is an attempt to fix #35. The changes from line 320-323 are really crude. However, I am not too familiar with how `xlink:href` is supposed to behave.
=> Fix the support for `use' elements.

svgnative/src/SVGDocumentImpl.cpp, svgnative/test/gradient-outside-defs.svg, svgnative/test/gradient-outside-defs.txt
I am not sure if this would be the best way to fix it. Instead of creating multiple `else if` statements in `ParseChild` and copy-pasting sections of code from `ParseResource`, it's probably better to write one `else if` in `ParseChild` and let `ParseResource` do the actual job. 
This should close #36.
=> Support gradient elements outside `defs`.

svgnative/ports/skia/SkiaSVGRenderer.cpp, svgnative/src/SVGDocumentImpl.cpp, svgnative/test/dash-array.txt
* odd-sized dash array is doubled for all backends.
* svgnative/test/dash-array.txt is updated for oddsized cases.
=> Add a support for dashed line to Skia backend.

README.md, svgnative/include/SVGDocument.h, svgnative/include/SVGRenderer.h, svgnative/src/SVGDocumentImpl.cpp, svgnative/src/SVGDocumentImpl.h, svgnative/src/SVGStringParser.cpp, svgnative/src/SVGStringParser.h, svgnative/test/elem-transform-on-parent.svg, svgnative/test/path.svg, svgnative/test/properties.svg, svgnative/test/svgLength.svg
Mostly documentation and comments; notable exception:
`SVGDocumentImpl::LengthType::kHorrizontal` => `SVGDocumentImpl::LengthType::kHorizontal`
boundnig -> bounding (1x)
comercial -> commercial (1x)
consitent -> consistent (1x)
decendants -> descendants (1x)
desandents -> descendants (1x)
foramts -> formats (1x)
graohic -> graphic (1x)
habe -> have (1x)
hiearchy -> hierarchy (1x)
horrizontal -> horizontal (23x)
negetive -> negative (7x)
opacty -> opacity (1x)
optinoal -> optional (2x)
roate -> rotate (1x)
separaetd -> separated (2x)
=> Fix some spelling errors

svgnative/ports/skia/SkiaSVGRenderer.cpp
For the side-by-side discussion for clip-rule and fill-rule, Skia port might be expected to support fill-rule. My patch call setFillType() method of SkPath object, before it is passed to drawPath().
I've checked their results by 2 samples at W3C's SVG spec page.
https://www.w3.org/TR/SVG11/images/painting/fillrule-nonzero.svg
is resulted as
https://www.w3.org/TR/SVG11/images/painting/fillrule-evenodd.svg
is resulted as
=> Skia: Support fill-rule.

svgnative/CMakeLists.txt, svgnative/ports/cairo/CairoSVGRenderer.cpp, svgnative/ports/cg/CGSVGRenderer.cpp, svgnative/ports/gdiplus/GDIPlusSVGRenderer.cpp, svgnative/src/SVGDocumentImpl.cpp
I found some lines have unrequired trailing spaces (some of them are mine, I apologize them). Here is a patch removing trailing spaces from *.cpp, *.h, *.c and *.txt.
=> Remove trailing spaces

svgnative/CMakeLists.txt, svgnative/ports/skia/SkiaSVGRenderer.cpp
* take <sk_sp>SkImage, return an oriented <sk_sp>SkImage or nullptr.
* determine the orientation from EXIF info, by using SkCodec.
* if the orientation is required, <sk_sp>SkImage is returned.
* if the orientation is not needed, nullptr is returned.
Add -Wno-pedantic (if not MSVC) to compile SkiaSVGRenderer.cpp,
because skcms.h (required by SkCodec.h) requires C11 feature.
=> Add getOrientedImage() function to resolve the issue (#53).

README.md
README.md recommends to install Boost into "C:\Platform Files\boost", but it might be a typo, because CMake's builtin Boost finder checks C:\Program Files.
=> fix some comments on Boost on Windows

svgnative/src/SVGStringParser.cpp
* SVGStringParser.cpp: Replace 'pos != end' by 'pos < end' to prevent overrunning.
=> Fix for Issue #62.

svgnative/src/SVGDocumentImpl.cpp
* SVGDocumentImpl.cpp: Check whether the XMLNode is valid before using it.
=> Fix for Issue #63.

svgnative/ports/cairo/CairoImageInfo.c
When a developer tries to build SVG Native Viewer with Cairo port, and if their system has IJS's genuine JPEG not JPEG-Turbo, the building would be stopped because JCS_EXT_ARGB is not defined. It is JPEG-Turbo extension.
This attribute is determined from input JPEG image by JPEG decoder, the client program cannot specify it. If the client program pass an extended JPEG image with alpha-channel but the library is linked to IJS JPEG decoder, the image would be dealt as broken data, so, we don't have to write special workaround.
=> Conditionalize JCS_EXT_ARGB, because it is an extension in JPEG-Turbo.

.gitignore, svgnative/CMakeLists.txt, svgnative/SVGNativeViewerLib-uninstalled.pc.in, svgnative/SVGNativeViewerLib.pc.in
* Enhancements for pkg-config files. Add "make install" target into CMakeLists.txt,
to separate SVGNativeViewerLib.pc and SVGNativeViewerLib-uninstalled.pc.
* Cairo and JPEG check is improved for non-Unix platforms.
=> Add "make install" target, and to-be-installed & uninstalled pkg-config files (originally PR #60)

svgnative/CMakeLists.txt
d1f8a2c cannot finish the linking of testC. To finish it, "-framework CoreFoundation" is added to the linker flag in CMakeLists.txt.
An archive library does no record its dependency, so the dependencies should be supplied by the linker flags explicitly, also it is added to pkg-config file.
=> CoreGraphics port: add "-framework CoreFoundation" to the linker flag to use libSVGNativeViewerLib.

svgnative/src/SVGNativeCWrapper.cpp
Sorry for overlooking this (if USE_STRING is undefined, C-wrapper cannot select Text/String port).
=> Fix a typo: USE_STRING might be a typo of USE_TEXT

svgnative/src/SVGNativeCWrapper.cpp
It seems that [SVGNativeCWrapper compile error around GDI+ header](https://circleci.com/gh/adobe/svg-native-viewer/655?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) might be caused by the lack of a few header files. I apologize that I could not find this error before.
=> include Win32 headers to compile SVGNativeCWrapper.cpp with GDI+.

.circleci/config.yml, svgnative/CMakeLists.txt, svgnative/ports/gdiplus/GDIPlusSVGRenderer.cpp, svgnative/ports/gdiplus/GDIPlusSVGRenderer.h
Fix for the issue #96.
* CMakeLists.txt: add explicit dependency to gdiplus.dll.
* GDIPlusSVGRenderer.{h,cpp}: move several inline functions from header to C++ source.
some Windows headers makes the symbol references from the inline functions in the class definition,
even if such functions are not used at all.
=> fix GDIPlus under -DSHARED=ON config

svgnative/example/testC/TestMain.c
Maybe it was my mistake that "Adobe Confidential" license is used in TestMain.c.
Using Apache License 2.0 would be better and consistent.
=> TestMain.c: change the license to APL 2.0

svgnative/src/SVGStringParser.cpp
SVGStringParser::ParsePaint() sets the initial value of 'result' to kInvalid. In some cases, the result is updated to kDisabled, but it is never updated to kSuccess, except of the case that ParseColor() updates it. Therefore, once the parental element sets "fill='none'", often the child elements cannot override it, like Issue #111.
This commit changes the initial value from kInvalid to kSuccess, and all 'return result' before changing 'result' are replaced by immediate 'return kInvalid'.
=> Fix for Issue #111: a valid fill attribute cannot override its parental "fill='none'" attribute.

svgnative/src/SVGStringParser.cpp
According to the [spec](https://www.w3.org/TR/SVG/paths.html#PathDataQuadraticBezierCommands), the 'T' and 't' only use the reflection of the last control point if the last command is Q/q/T/t
Following is an SVG that contains a character "c", without the patch it renders incorrectly:
```
<svg
xmlns="http://www.w3.org/2000/svg" width="108.21ex" height="24.52ex" role="img" focusable="false" viewBox="0 -833.9 4783 1083.9"
xmlns:xlink="http://www.w3.org/1999/xlink" style="vertical-align: -0.566ex;">
<defs>
<path id="MJX-2-TEX-N-63" d="M370 305T349 305T313 320T297 358Q297 381 312 396Q317 401 317 402T307 404Q281 408 258 408Q209 408 178 376Q131 329 131 219Q131 137 162 90Q203 29 272 29Q313 29 338 55T374 117Q376 125 379 127T395 129H409Q415 123 415 120Q415 116 411 104T395 71T366 33T318 2T249 …
```
=> Fix incorrect 'T'/'t' implementation

.gitignore, svgnative/example/testD2D/TestD2D.cpp, svgnative/example/testD2D/basewin.h, svgnative/include/svgnative/ports/d2d/D2DSVGRenderer.h, svgnative/src/ports/d2d/D2DSVGRenderer.cpp
Fix the over-release issue with a ID2D1PathGeometry object and update the test app from a D2D test sample source.
The over-release issue can be fixed by avoiding a copy of an D2DSVGPath but to make D2D objects generally copyable and handle lifetime issues all D2D objects are now wrapped by a smart pointer (CComPtr). The only downside here is that CComPtr is part of Windows' Active Template Library (ATL) which might not be available everywhere.
=> D2D port fixes

svgnative/src/ports/cg/CGSVGRenderer.cpp
Fixes #144. The bug was simple, the angle being passed in to `CGAffineTransformRotate` is in degrees when it should be in radians.
=> Fix the rotation problem in CG port

svgnative/src/ports/cairo/CairoSVGRenderer.cpp, svgnative/src/ports/cg/CGSVGRenderer.cpp
This should solve #137.
There is inconsistency in the way concatenation is handled across the four ports and that's what leads to this behavior. You can also observe the same behavior by having a node with a `transform` attribute that has a `matrix` transform following other transforms such as `translate` or `scale` or `rotate`.
This PR should be reviewed with a lot of care as I'm not fully sure if my analysis is correct, but I present it here for you to review it.
I think the way SNV expects the `Transform` interface to work is such that each new transformation is supposed to happen before everything that came before it. For example, take a look at the following three calls:
```
matrix.Translate(500, 500); // 3
matrix.Rotate(45); // 2
matrix.Translate(-500, -500); // 1
```
The shape …
=> Fix transform concatenation problem

svgnative/src/ports/cairo/CairoSVGRenderer.cpp, svgnative/src/ports/cg/CGSVGRenderer.cpp, svgnative/src/ports/gdiplus/GDIPlusSVGRenderer.cpp, svgnative/src/ports/skia/SkiaSVGRenderer.cpp
This should fix #151. Surprisingly, the GDI+ port already had the necessary conversion code while Cairo didn't. Skia and CG both have API calls for Quadratic Curves and yet they were not being used.
=> Fix Quadratic Beziers problem

svgnative/src/ports/skia/SkiaSVGRenderer.cpp
This fixes #154 partially. I've done the Skia fix. 
@dirkschulze For cairo, you pointed out that they have APIs for transparency layers. Could you point them to me, I couldn't find something simple.
=> fix skia call to saveLayerAlpha

svgnative/src/ports/skia/SkiaSVGRenderer.cpp
If the image data passed to SkCodec::MakeFromData is not recognized as
image data the SkCodec::MakeFromData may return nullptr. Check for this
failure and return instead of crashing.
=> Check SkCodec was created before getting origin.

svgnative/example/testSkia/TestSkia.cpp
Some IWYU to allow TestSkia.cpp to build with newer versions of Skia
where SkEncodedImageFormat is not implicitly included through other
includes.
=> Include SkEncodedImageFormat.h in TestSkia.cpp.

svgnative/include/svgnative/ports/skia/SkiaSVGRenderer.h, svgnative/src/ports/skia/SkiaSVGRenderer.cpp
The `SkiaSVGImageData` destructor must destroy an `sk_sp<SkImage>` member.
However, `SkiaSVGRenderer.h` only has a forward declaration of `SkImage` so
the default inline destructor cannot destruct the `SkImage` unless the
translation unit which includes `SkiaSVGRenderer.h` pulls in the full
definition of `SkImage`. Remove this awkward situation by defining the
destructor in `SkiaSVGRenderer.cpp`, which does have a full definition of
`SkImage`.
=> Explicitly define ~SkiaSVGImageData

svgnative/src/xml/ExpatXMLParser.cpp
Both `<string>` and `<string.h>` are needed in ExpatXMLParser.cpp.
=> Include <string> in ExpatXMLParser.cpp

svgnative/src/SVGDocumentImpl.cpp, svgnative/src/SVGStringParser.cpp, svgnative/src/SVGStringParser.h, svgnative/test/properties.svg, svgnative/test/properties.txt
Support of Percentage values when specifies offset/opacity for stroke/fill properties 
Make a ParseNumber function generic, now work for both as a number or % values
Modified testcase which initially does not support % values
=> support number or percentage values for offset/opacity values 

svgnative/src/ports/skia/SkiaSVGRenderer.cpp
in Skia ports, when we are computing bounding box coordinates, basically it transforms coordinates according to 3x3 matrix which will change the bounds value. we do need change according to 3x3 matrix.
=> minor fix in Bounding Box specifically only for  skia port

svgnative/src/SVGNativeCWrapper.cpp
The ApplicationServices is not available on those platform.
By replacing with CoreServices, I can sucessfully build on all Apple platforms:
+ macOS 12 SDK
+ iOS 15 SDK
+ tvOS 15 SDK
+ watchOS SDK 8
https://github.com/adobe/svg-native-viewer/issues/180
Fix compile issue on iOS/tvOS/watchOS
Testing build using both CMake and Xcode geneted project
Note: I'm using the source code and a modified CMake script to support iOS/tvOS/watchOS. This repo can support for those mobile platforms as well, but this is another PR or issue, so I didn't link here.
=> Fix iOS/tvOS/watchOS platform support
